### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by phonedeveloper** [doppelhub/Honda_Insight_LiBCM#2]
If the CC-by-SA license mentioned in the README is intentional (see https://opensource.stackexchange.com/questions/1717/why-is-cc-by-sa-discouraged-for-code) the convention is to place that license in LICENSE.txt in the project root.

Since the project includes code with different licenses (the LTC library, for example) that require attribution, a list of these files and their licenses may also be needed in LICENSE.txt.  (note, IANAL)

**Comment by doppelhub** [comment]
License is intentional.  Note LiBCM is primarily a hardware project, and I don't mind the one-way licensing issue CC by-SA introduces.  I prefer CC for many reasons.
